### ISSUE TITLE
Some thoughts about possible improvements

### ISSUE THREAD

**Issue by jschlieber** [ryo33/react-throttle-render#4]
Hi, I like this nice little project and would like to share some thoughts about possible improvements. 

1. I recently tried to use `throttleProps` with a pure functional component, and it didn't work. It constantly rerendered although throttled. Then I realized that of course a pure functional component does not implement a `shouldComponentUpdate` method and thus it renders whenever the `render` method of the `Throttle` wrapper gets called. And in fact the `Throttle` component `render` method gets called on each and every prop update. Thus i suggest implementing `shouldComponentUpdate` in the `Throttle` component itself, so it also works with pure functional components out of the box.

2. Provide a Higher Order Component generating function, like this:
```javascript
function throttleProps(wait, options) {
  return function(component) {
     ...
  };
}
```
So the usage would change to
```javascript
const ThrottledComponent = throttleProps(50)(VeryBigRenderComponent);
```
This would allow a better integration with react functional utility libraries such as [recompose](https://github.com/acdlite/recompose). (BTW: they already have a `throttleProps` utility in their pull requests)

**Comment by ryo33** [comment]
Thanks for sending this issue.
I fully agree with them.
I'll start right now.
